# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
!pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 68.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 64.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 44.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 70.2 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

In [2]:
import torch

In [4]:
# Import torch

random_tensor = torch.rand(7, 7)

# Create random tensor
random_tensor

tensor([[0.5847, 0.0358, 0.9400, 0.1419, 0.2844, 0.2992, 0.6947],
        [0.1808, 0.4551, 0.7686, 0.5193, 0.3271, 0.6370, 0.5734],
        [0.1884, 0.6163, 0.1534, 0.5918, 0.6193, 0.0051, 0.6100],
        [0.8398, 0.3395, 0.3871, 0.0408, 0.8042, 0.1791, 0.6337],
        [0.5007, 0.8717, 0.5756, 0.3622, 0.9388, 0.5861, 0.1745],
        [0.6541, 0.5435, 0.8037, 0.3547, 0.1652, 0.7745, 0.4593],
        [0.0304, 0.0073, 0.3106, 0.2281, 0.7396, 0.0092, 0.4103]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor

another_tensor = torch.rand(1, 7)

# Perform matrix multiplication

another_tensor.T, another_tensor.T.shape

(tensor([[0.2636],
         [0.6452],
         [0.7166],
         [0.1645],
         [0.5079],
         [0.4449],
         [0.0607]]),
 torch.Size([7, 1]))

In [11]:
multiplicated_tensor = torch.matmul(random_tensor, another_tensor.T)
multiplicated_tensor

tensor([[1.1940],
        [1.4619],
        [1.0084],
        [1.2512],
        [1.9147],
        [1.6137],
        [0.6774]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [15]:
# Set manual seed

torch.manual_seed(0)

# Create two random tensors

random_tensor = torch.rand(7, 7)
another_tensor = torch.rand(7, 1)

# Matrix multiply tensors
new_tensor = torch.matmul(random_tensor, another_tensor)
new_tensor, new_tensor.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [16]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [20]:
# Set random seed

torch.manual_seed(1234)

random_tensor = torch.rand(2, 3)
another_tensor = torch.rand(2, 3)

# Check for access to GPU
device_name = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
device = torch.device(device_name)
random_tensor = random_tensor.to(device)
another_tensor = another_tensor.to(device)

random_tensor, another_tensor

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [23]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(random_tensor, another_tensor.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max

max_element = torch.max(tensor_C)

# Find min

min_element = torch.min(tensor_C)

max_element, min_element

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max

max_index = torch.argmax(tensor_C)

# Find arg min
min_index = torch.argmin(tensor_C)

max_index, min_index

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [29]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(1, 1, 1, 10)
print(tensor_D, tensor_D.shape)
# Remove single dimensions
tensor_D_without_one_dimentions = torch.squeeze(tensor_D)

# Print out tensors and their shapess
tensor_D_without_one_dimentions, tensor_D_without_one_dimentions.shape

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])


(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))